.\" Manpage for mycommand
.\" Contact your local UNIX guru if you do not understand this.
.TH mycommand 1 "January 2024" "MyCommand Manual"

.SH NAME
mycommand \- your custom command

.SH SYNOPSIS
.B mycommand
[\fIOPTION\fR]

.SH DESCRIPTION
This is a simple example of a custom Linux command.

.SH OPTIONS
.TP
.B \-\-help
Display help message.

.TP
.B \-\-version
Display version information.

.SH AUTHOR
Your Name

.SH SEE ALSO
.BR man (1)
